ERROR: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc4ff58200>: Failed to establish a new connection: [Errno 111] Connection refused')) at 2024-10-01 02:30:35.165470
ERROR: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7df80cd02300>: Failed to establish a new connection: [Errno 111] Connection refused')) at 2024-10-01 02:31:39.106790
